'use strict';

module.exports = [
    {
        "id" : "1",
        "title": "Dune",
        "year": "1965",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/199",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda aksdkjnsakjdsa dsa k dksa kdjna skndksakdjnaskjndsakd kna kdjansd akd ksa dkjsa nd",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "2",
        "title": "Dune Messiah",
        "year": "1969",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/12",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "3",
        "title": "Children of Dune ",
        "year": "1976",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/13",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "4",
        "title": "God Emperor of Dune",
        "year": "1981",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/233",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "5",
        "title": "Heretics of Dune",
        "year": "1984",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/240",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "6",
        "title": "Chapterhouse: Dune",
        "year": "1985",
        "author": "Frank Herbert",
        "wiki_url": "https://picsum.photos/211",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "7",
        "title": "House Atreides",
        "year": "1999",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/202",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "8",
        "title": "House Harkonnen",
        "year": "2000",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/202",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "9",
        "title": "House Corrino",
        "year": "2001",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/201",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "10",
        "title": "The Butlerian Jihad",
        "year": "2002",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/204",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "11",
        "title": "The Machine Crusade",
        "year": "2003",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/205",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "12",
        "title": "The Battle of Corrin",
        "year": "2004",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/206",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "13",
        "title": "Hunters of Dune ",
        "year": "2006",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/207",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "14",
        "title": "Sandworms of Dune",
        "year": "2007",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/208",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "15",
        "title": "Paul of Dune",
        "year": "2008",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/209",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "16",
        "title": "The Winds of Dune",
        "year": "2009",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/210e",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "17",
        "title": "Sisterhood of Dune",
        "year": "2012",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/219",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "18",
        "title": "Mentats of Dune",
        "year": "2014",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/222",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "19",
        "title": "Navigators of Dune",
        "year": "2016",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/129",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "20",
        "title": "Dune: The Duke of Caladan",
        "year": "2020",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/111",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "21",
        "title": "Dune: The Lady of Caladan",
        "year": "2021",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/134",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
    {
        "id" : "22",
        "title": "Dune: The Heir of Caladan",
        "year": "TBA",
        "author": ["Brian Herbert", "Kevin J. Anderson"],
        "wiki_url": "https://picsum.photos/124",
        "deskripsi" : "jjjjsjnsjsnjdnja jndjnadnasndjasjnda",
        "pages" : "1092",
        "terbit": "3/10/2001",
        "bahasa": "Indonesia",
        "penerbit": "depelover",
        "review": '4',
        "sinopsis": "Buku ini adlaahaas jsandjnsandsa n dandjasda sdasndjsadnkasd asdksakd nas kdjnsak dkna ndkjsand sakdnkjsandk sakd naks dnsa d sakjd aksjdnokjsa dkna kdj sakjd aksj dkjsa dknsakjdnsakj dkajs",
        "isbn" : "2313141"
    },
]